version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dicri-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@assw0rd123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  api:
    build: ./backend
    container_name: dicri-api
    environment:
      - DB_USER=sa
      - DB_PASSWORD=P@assw0rd123
      - DB_SERVER=db
      - DB_NAME=DicriDB
      - JWT_SECRET=supersecret
    ports:
      - "3000:3000"
    depends_on:
      - db

  web:
    build: ./frontend
    container_name: dicri-web
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mssqldata:
